apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace "expo.modules.clickercore"
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35
    }

    // [추가] 자바 폴더 안에 있는 코틀린 소스를 인식하게 하는 설정
    sourceSets {
        main.java.srcDirs += 'src/main/java'
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation project(':expo-modules-core')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}
