apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    // 매니페스트 에러를 방지하기 위한 네임스페이스 정의
    namespace "expo.modules.clickercore"
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 24 
        targetSdkVersion 35
        versionCode 1
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    // 코틀린과 자바 소스 폴더 통합
    sourceSets {
        main {
            java.srcDirs = ['src/main/java']
            kotlin.srcDirs = ['src/main/java']
        }
    }

    buildFeatures {
        buildConfig true
    }

    // 자바 17 환경 준수 (안드로이드 16 빌드 필수 조건)
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    lintOptions {
        abortOnError false
    }
}

dependencies {
    implementation project(':expo-modules-core')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    
    // UI 및 포그라운드 서비스를 위한 필수 라이브러리
    implementation "androidx.core:core-ktx:1.12.0"
    implementation "androidx.appcompat:appcompat:1.6.1"
}
